typography_spectrum: 0.018336109584197402
color:
  brandStrength: 0.16157935606315732
  lightness: 0.3801460126414895
  saturation: 0.008538103895261884
  rhythmicContrast: 0.8944173671770841
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/4903a662-1b07-4d71-83d0-ca6683fa8f86.png
layout_spectrum: 0.5672922844532877
author:
  name: Magda Jagri
  email: magda@magdajagri.com
  url: www.magdajagri.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fc80b88-5f1c-4c00-9e7a-f5357d4bf138.png
name: MAGDA JAGRI
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6663460e-5784-4f25-b4ad-3603809e3e40.png
title: MAGDA JAGRI
description: Welcome
